-- supabase/migrations/20250914211000_create_minoristas_table.sql

-- Creación de la tabla de minoristas
CREATE TABLE public.minoristas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    url_base TEXT NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comentarios para la tabla y columnas
COMMENT ON TABLE public.minoristas IS 'Tabla para almacenar información de los minoristas de donde se extraen los productos.';
COMMENT ON COLUMN public.minoristas.id IS 'Identificador único del minorista.';
COMMENT ON COLUMN public.minoristas.nombre IS 'Nombre del minorista (ej. Amazon, Target).';
COMMENT ON COLUMN public.minoristas.url_base IS 'URL base del sitio web del minorista.';
COMMENT ON COLUMN public.minoristas.activo IS 'Indica si el minorista está activo para el rastreo.';
COMMENT ON COLUMN public.minoristas.created_at IS 'Fecha y hora de creación del registro del minorista.';

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.minoristas ENABLE ROW LEVEL SECURITY;

-- Crear política de acceso total para el rol de servicio
CREATE POLICY "Acceso Total Rol Servicio Minoristas"
ON public.minoristas
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
