-- supabase/migrations/20250914211500_create_historial_precios_table.sql

-- Creación de la tabla de historial de precios
CREATE TABLE public.historial_precios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL,
    id_minorista BIGINT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    fecha_registro TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Clave foránea a la tabla productos
    CONSTRAINT fk_producto
        FOREIGN KEY (id_producto)
        REFERENCES public.productos (id)
        ON DELETE CASCADE,
        
    -- Clave foránea a la tabla minoristas
    CONSTRAINT fk_minorista
        FOREIGN KEY (id_minorista)
        REFERENCES public.minoristas (id)
        ON DELETE CASCADE
);

-- Comentarios para la tabla y columnas
COMMENT ON TABLE public.historial_precios IS 'Tabla para almacenar el historial de precios de los productos en diferentes minoristas.';
COMMENT ON COLUMN public.historial_precios.id IS 'Identificador único del registro de historial de precio.';
COMMENT ON COLUMN public.historial_precios.id_producto IS 'Clave foránea al producto asociado.';
COMMENT ON COLUMN public.historial_precios.id_minorista IS 'Clave foránea al minorista donde se registró el precio.';
COMMENT ON COLUMN public.historial_precios.precio IS 'Precio registrado en ese momento.';
COMMENT ON COLUMN public.historial_precios.fecha_registro IS 'Fecha y hora en que se registró el precio.';

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.historial_precios ENABLE ROW LEVEL SECURITY;

-- Crear política de acceso total para el rol de servicio
CREATE POLICY "Acceso Total Rol Servicio Historial Precios"
ON public.historial_precios
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
