-- supabase/migrations/20250914210000_create_products_table.sql

-- Creación de la tabla de productos
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    product_url TEXT NOT NULL UNIQUE,
    image_url TEXT,
    last_scraped_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comentario sobre la tabla para claridad
COMMENT ON TABLE public.products IS 'Tabla para almacenar información de productos rastreados.';

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Crear política de acceso total para el rol de servicio
CREATE POLICY "Service Role Full Access"
ON public.products
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);